In [1]:
import numpy as np

In [2]:
# initialize a 1 D array
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) # 2-d array
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a = np.zeros((5,6))
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
a = np.ones((5,6,2))
a

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [7]:
import pandas as pd
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})
df

A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [8]:
df.to_numpy()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]], dtype=int64)

In [9]:
# indexing and slicing
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a[1][2]

6

In [11]:
# slicing
a[0:2, 1:2]

array([[2],
       [5]])

In [13]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a.T # transpose flips rows and columns

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [15]:
a.flatten() # flattens the array to 1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
a.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [21]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.sum(a, axis=0)  # sum along columns

array([22, 26, 30])

In [23]:
np.sum(a, axis = 1)  # sum along rows

array([ 6, 15, 24, 33])

In [24]:
np.sum(a)

78

In [26]:
a = np.array([[1,2,3],[3,2,7],[4,6,9]])
a

array([[1, 2, 3],
       [3, 2, 7],
       [4, 6, 9]])

In [30]:
b = np.array([[-1,2,1],[4,-2,6],[3,10,5]])
b

array([[-1,  2,  1],
       [ 4, -2,  6],
       [ 3, 10,  5]])

In [31]:
a + b

array([[ 0,  4,  4],
       [ 7,  0, 13],
       [ 7, 16, 14]])

In [32]:
a-b

array([[ 2,  0,  2],
       [-1,  4,  1],
       [ 1, -4,  4]])

In [33]:
np.add(a,b)

array([[ 0,  4,  4],
       [ 7,  0, 13],
       [ 7, 16, 14]])

In [34]:
np.subtract(a,b)

array([[ 2,  0,  2],
       [-1,  4,  1],
       [ 1, -4,  4]])

In [36]:
np.dot(a,b)

array([[16, 28, 28],
       [26, 72, 50],
       [47, 86, 85]])

In [37]:
a*b

array([[-1,  4,  3],
       [12, -4, 42],
       [12, 60, 45]])

In [38]:
np.multiply(a,b)

array([[-1,  4,  3],
       [12, -4, 42],
       [12, 60, 45]])

In [40]:
np.dot(np.linalg.inv(a), b)

array([[ 6.   ,  4.   ,  2.   ],
       [-0.875,  3.5  , -0.875],
       [-1.75 , -3.   ,  0.25 ]])

In [41]:
np.linalg.solve(a, b)  # solves the linear equation Ax = b

array([[ 6.   ,  4.   ,  2.   ],
       [-0.875,  3.5  , -0.875],
       [-1.75 , -3.   ,  0.25 ]])

In [ ]:
# Broadcasting

In [43]:
np.zeros((1,224,224,3)) + 1

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        ...,

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

In [44]:
a = np.array([[1,2,3],[3,2,7],[4,6,9]])
a

array([[1, 2, 3],
       [3, 2, 7],
       [4, 6, 9]])

In [45]:
a + np.array([2,4,6])

array([[ 3,  6,  9],
       [ 5,  6, 13],
       [ 6, 10, 15]])

In [46]:
a.ndim

2

In [47]:
a = np.zeros((1,224,224,3))
a.ndim

4

In [48]:
a.size

150528

In [49]:
a = np.array([[1,2,3],[3,2,7],[4,6,9]])
a.shape

(3, 3)

In [50]:
a = np.array([1, 2, 3])
a.shape

(3,)

In [52]:
b = a.T
b

array([1, 2, 3])

In [54]:
b.shape

(3,)

In [55]:
np.amin(a)

1

In [56]:
np.where(a==np.amin(a))  # returns the indices of the minimum value in the array

(array([0], dtype=int64),)

In [ ]:
# vectoriazing

In [58]:
a = np.array([[5,2,-8,2],[2,3,6,1]])
a

array([[ 5,  2, -8,  2],
       [ 2,  3,  6,  1]])

In [59]:
def myfucn(a,b):
    if a == b:
        return 0
    return a + b

In [60]:
vfunc = np.vectorize(myfucn)

In [61]:
vfunc(a, 2)

array([[ 7,  0, -6,  0],
       [ 0,  5,  8,  3]])

In [62]:
np.save('my_array.npy', a)  # save the array to a file

In [63]:
arr = np.load('my_array.npy')
arr

array([[ 5,  2, -8,  2],
       [ 2,  3,  6,  1]])